name: TGeniusLobby
version: '${project.version}'
main: com.viznyuk.minecraft.tgeniuslobby.TGeniusLobby
api-version: '1.20'
commands:
  lobby:
    description: Your description
    usage: /lobby {option} {option}
    permission:
      tgeniuslobby.lobby.self
    aliases: [ hub, spawn ]


permissions:
  tgeniuslobby.lobby.self:
    description: /lobby
    children:
      tgeniuslobby.lobby.others: true
      tgeniuslobby.lobby.usage_while_in_combat: false
      tgeniuslobby.lobby.set_lobby: true
      tgeniuslobby.lobby.bypass_autoteleport: false
      tgeniuslobby.lobby.bypass_time: false


  tgeniuslobby.lobby.others:
    description: You can /lobby everybody yoo wand
